apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: go-app
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./go-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: go-app
  targetNamespace: default